/** Branded storefront + settings for tescommerce.com */
export const TESCOMMERCE_SLUG = "tescommerce";
export const TESCOMMERCE_DOMAIN = "tescommerce.com";

export const tescommerceSettings = {
  defaultLocale: "en",
  enabledLocales: ["en"],
  currency: "USD",
  timezone: "America/New_York",
  primaryColor: "#0f766e",
  faviconUrl: null as string | null,
  contactEmail: "hello@tescommerce.com",
  contactPhone: "+1 (555) 010-2000",
  businessAddress: "120 Commerce Ave, Austin, TX 78701, USA",
  emailFromName: "Tescommerce",
  emailReplyTo: "hello@tescommerce.com",
  seoTitle: "Tescommerce — Shop quality products online",
  seoDescription:
    "Tescommerce is your trusted online store for curated products, fast shipping, and secure checkout.",
  seoOgImageUrl: null as string | null,
  checkoutFooterText: "Secure checkout powered by Stripe. Questions? hello@tescommerce.com",
};

export const tescommerceTheme = {
  buttonStyle: "rounded" as const,
  containerMaxPx: 1280,
  fontFamily: '"Plus Jakarta Sans", system-ui, sans-serif',
  secondaryColor: "#115e59",
  pageBgColor: "#ffffff",
  blockGap: "md" as const,
  announcementEnabled: true,
  announcementText: "Free shipping on orders over $75 — use code SHIP75 at checkout",
  announcementColor: "#0f766e",
  navLinks: [
    { label: "Shop", path: "/collections", header: true, footer: false },
    { label: "New arrivals", path: "/collections?sort=newest", header: true, footer: false },
    { label: "Sale", path: "/collections?sale=1", header: true, footer: false },
    { label: "Contact", path: "/#contact", header: true, footer: true },
  ],
  socialLinks: {
    instagram: "https://instagram.com/tescommerce",
    tiktok: "https://tiktok.com/@tescommerce",
  },
  trustBadgesEnabled: true,
  homeBlocks: [
    {
      id: "blk_tes_hero",
      type: "hero",
      contentWidth: "full",
      paddingY: "none",
      align: "center",
      title: "Shop smarter with Tescommerce",
      subtitle: "Curated products, fast delivery, and checkout you can trust.",
      ctaLabel: "Shop now",
      ctaPath: "/collections",
      bgColor: "#0f766e",
      textColor: "#ffffff",
    },
    {
      id: "blk_tes_features",
      type: "features",
      title: "Why shoppers choose us",
      paddingY: "lg",
      features: [
        { title: "Fast shipping", text: "Most orders ship within 24 hours." },
        { title: "Secure payments", text: "Encrypted checkout with Stripe." },
        { title: "Easy returns", text: "30-day hassle-free returns." },
      ],
    },
    {
      id: "blk_tes_products",
      type: "products",
      title: "Bestsellers",
      paddingY: "lg",
      productColumns: 4,
      productLimit: 8,
    },
    {
      id: "blk_tes_banner",
      type: "text_banner",
      align: "center",
      bgColor: "#f0fdfa",
      textColor: "#134e4a",
      title: "Spring collection is live — up to 25% off selected items",
      ctaLabel: "View sale",
      ctaPath: "/collections?sale=1",
      paddingY: "md",
    },
    {
      id: "blk_tes_reviews",
      type: "reviews",
      title: "What customers say",
      paddingY: "md",
      align: "center",
    },
    {
      id: "blk_tes_newsletter",
      type: "newsletter",
      title: "Join the Tescommerce list",
      subtitle: "Get new drops, offers, and tips — no spam.",
      align: "center",
      bgColor: "#f4f4f5",
      paddingY: "lg",
    },
    {
      id: "blk_tes_contact",
      type: "contact_form",
      title: "Contact us",
      subtitle: "We reply within one business day.",
      body: "Questions about orders, products, or partnerships.",
      paddingY: "lg",
    },
  ],
};
